name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "lts/*"
    - name: Build
      run: |
        npm install web-ext
        npm run build:neat-url
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: web-ext-artifacts/neat_url-5.0.0.zip